config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get 'top' => 'homes#top'
  resources :books
  root to: 'homes#top'
  
  #get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  #get 'books/:id' => 'books#show', as: 'book'
 
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord #::Base
  validates :title, presence: true
  validates :body, presence: true
  
  #validate :add_error_sample
 
  #def add_error_sample
    #if title.blank?
     # errors[:base] << "Title can't be blank"
    #end
 
    #if body.blank?
     # errors[:base] << "Body can't be blank"
    #end
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end 
  
  def index
    @books = Book.all
    @book = Book.new
  end 
  
  def show
    @book = Book.find(params[:id])  
  end 
  
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :index
    end 
  end 
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book.id)
    else
    render :edit
    end 
  end
  
  def edit
    @book = Book.find(params[:id])
  end 
 
  def destroy
    book = Book.find(params[:id])  
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to '/books'  
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end 

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<p class="p-notice"><%= flash[:notice] %></p>
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <div id="error_explanation">
  <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>  
  </div>
  <div class="field_with_errors">
   <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>

<%= form_with model: @book do |f| %>

  <p>Title</p>
  <%= f.text_field :title %>
  
  <p>Body</p>
  <%= f.text_area :body %>
  
  <br><%= f.submit 'Update Book' %>
  
<% end %>

<%= link_to "Show", book_path(@book.id) %>|<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<p class="p-notice"><%= flash[:notice] %></p>


<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
  </tbody>
 <% end %> 
</table>

<h2>New book</h2>
<% if @book.errors.any? %>
  <div id="error_explanation">
  <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>  
  </div>
  <div class="field_with_errors">
   <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>

<%= form_with model: @book, url: "/books", method: :post do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Body</p>
  <%= f.text_area :body %>
	
  <br>
  </br>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<p class="p-notice"><%= flash[:notice] %></p>
<p class="p-margin">
<strong>Title: </strong><%= @book.title %><br>
</p>
<p class="p-margin">
<strong>Body: </strong><%= @book.body %><br>
</p>
<%= link_to "Edit", edit_book_path(@book.id) %>|<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1 class="headline">
    ようこそ
    <strong>Bookers</strong>
    へ!</h1>

<p class="p-margin">
    <strong>Bookers</strong>
    では、さまざまな書籍に関するあなたの意見や
    </p>

<p class="p-margin">印象を共有し交換することができます</p>

<p class="p-margin">
    <%= link_to 'start', books_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>